config/routes.rb
CurrencyTracker::Application.routes.draw do
  resources :visits

  devise_for :users

  root :to => "currencies#index"
  
  resources :countries, :except => [:new, :destroy]

  resources :currencies, :only => [:index, :show, :update]

end

app/models/country.rb
class Country < ActiveRecord::Base
  self.primary_key = :id
  attr_accessible :id, :name, :code, :visited, :user_id

  validates_presence_of :name
  validates_presence_of :code
  validates_uniqueness_of :code, :scope => :user_id, :allow_blank => true

  has_many :currencies

  belongs_to :user

  after_commit :create_visit

  accepts_nested_attributes_for :currencies, :allow_destroy => true

  scope :visited, :conditions => { :visited => true }
  scope :not_visited, :conditions => { :visited => false }

  def create_visit
    countryNumber = Country.visited.count
    Visit.create(:number => countryNumber)
  end
end

app/models/currency.rb
class Currency < ActiveRecord::Base
  self.primary_key = :id
  attr_accessible :id, :name, :code, :country_code, :country_id

  validates_presence_of :name
  validates_presence_of :code
  validates_uniqueness_of :code, :scope => :country_id, :allow_blank => true

  belongs_to :country

  def self.collected
    all.select {|currency| currency.collected? }
  end

  def self.not_collected
    all.reject {|currency| currency.collected? }
  end

  def collected?
    country.nil? ? false : country.visited?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  after_commit :seed

  has_many :countries

  def seed
    DataUpdater.update unless user_has_countries
  end

  def user_has_countries
    user_id = self.id
    !Country.find_by_user_id(user_id).nil?
  end
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  attr_accessible :id,:number,:created_at

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_filter :authenticate_user!

  # GET /countries
  # GET /countries.xml
  def index
    @countries = current_user.countries.all
    @visits = Visit.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @countries }
    end
  end

  # GET /countries/1
  # GET /countries/1.xml
  def show
    @country = current_user.countries.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @country }
    end
  end

  # GET /countries/1/edit
  def edit
    @country = current_user.countries.find(params[:id])
  end

  # POST /countries
  # POST /countries.xml
  def create
    @country = current_user.countries.new(params[:country])

    respond_to do |format|
      if @country.save
        format.html { redirect_to(@country, :notice => 'Country was successfully created.') }
        format.xml  { render :xml => @country, :status => :created, :location => @country }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @country.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /countries/1
  # PUT /countries/1.xml
  def update
    @country = current_user.countries.find(params[:id])

    respond_to do |format|
      if @country.update_attributes(params[:country])
        format.js   
        format.html { redirect_to(@country, :notice => 'Country was successfully updated.') }
        format.xml  { head :ok }
      else
        format.js
        format.html { render :action => "edit" }
        format.xml  { render :xml => @country.errors, :status => :unprocessable_entity }
      end
    end
  end
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  before_filter :authenticate_user!

  # GET /currencies
  # GET /currencies.xml
  def index
    get_currencies
    @visits = Visit.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @currencies }
    end
  end

  def get_currencies
    @currencies = []

    current_user.countries.each do |country|
      country.currencies.each do |currency| 
        @currencies << currency
      end
    end
  end

  # GET /currencies/1
  # GET /currencies/1.xml
  def show
    get_currencies
    
    if Currency.find(params[:id]).country.user == current_user
      @currency = Currency.find(params[:id]) 

      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @currency }
      end
    else
      # Redirect for those who are not authorized
      redirect_to currencies_path
    end
  end

  def update
    @currency = Currency.find(params[:id])
    @country = @currency.country
    
    respond_to do |format|
      if @country.update_attributes(:visited => params[:currency][:collected])
        format.js   
        format.html { redirect_to(@country, :notice => 'Country was successfully updated.') }
        format.xml  { head :ok }
      else
        format.js
        format.html { render :action => "edit" }
        format.xml  { render :xml => @country.errors, :status => :unprocessable_entity }
      end
    end
  end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/views/countries/_form.html.erb
<%= form_for(@country) do |f| %>
  <% if @country.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@country.errors.count, "error") %> prohibited this country from being saved:</h2>

      <ul>
      <% @country.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :visited %><br />
    <%= f.check_box :visited %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/countries/edit.html.erb
<h1>Editing country</h1>

<%= render 'form' %>

<%= link_to 'Show', @country %> |
<%= link_to 'Back', countries_path %>

app/views/countries/index.html.erb
<section>
  <div id="visited_countries_chart" class="simple_pie_chart" width='300px' height='100px'>
    <table>
      <tr>
        <th>Visited</th>
        <td><%= Country.visited.count %></td>
      </tr><tr>
        <th>Not Visited</th>
        <td><%= Country.not_visited.count %></td>
      </tr>
    </table>
  </div>

  <h1>Countries</h1>
  
  <p>
  </p>

  <div id="placeholder" style="width:500px;height:200px;top:50px;margin-bottom:50px;"></div>


  <table>
    <tr>
      <th>Name   <%= text_field_tag :search %></th>
      <th>Code</th>
      <th>Visit  <span id='checkallbox'>(<%= check_box :visit, :all %>Check all)</span></th>
      <th></th>
      <th></th>
    </tr>

  <% @countries.each do |country| %>
    <tr>
      <td><%= country.name %></td>
      <td><%= country.code %></td>
      <td><%= form_for country, remote: true do |f| %>
            <%= f.check_box :visited %>
          <% end %><div><%= country.visited? ? 'Visited' : 'Not Visited' %></div></td>
      <td><%= link_to 'Show', country %></td>
      <td><%= link_to 'Edit', edit_country_path(country) %></td>
    </tr>
  <% end %>
  </table>
</section>

<script type="text/javascript">
$(function () {

    var visits = [<% @visits.each do |visit| %>[new Date('<%= visit.created_at %>'), <%= visit.number %>],<% end %>];

    $.plot($("#placeholder"), [ visits ], {xaxis: { mode: 'time',timeformat: "%m/%d/%y"}});
});
</script>

app/views/countries/new.html.erb
<h1>New country</h1>

<%= render 'form' %>

<%= link_to 'Back', countries_path %>

app/views/countries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @country.name %>
</p>

<p>
  <b>Code:</b>
  <%= @country.code %>
</p>

<p>
  <b>Status:</b>
  <%= @country.visited? ? 'Visited' : 'Not Visited' %>
</p>

<p>
  <b>Currencies:</b>
  <ul>
    <% @country.currencies.each do |currency| %>
      <li><%= link_to currency.name, currency %></li>
    <% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_country_path(@country) %> |
<%= link_to 'Back', countries_path %>